name = "mentionpilot-web"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"
assets = { directory = ".open-next/assets" }

[vars]
NODE_ENV = "production"
NEXTAUTH_URL = "https://mentionpilot-web.sarthakagrawal927.workers.dev"

[[d1_databases]]
binding = "AUTH_DB"
database_name = "mentionpilot-auth"
database_id = "1b55ebb6-f563-4e0e-9cb4-ca0bff078fbe"
