export interface DirectoryEntry {
  slug: string;
  name: string;
  url: string;
  category: 'ai-tools' | 'product' | 'startup' | 'developer' | 'seo' | 'social' | 'review' | 'free-listing';
  description: string;
  has_api: boolean;
  difficulty: 'easy' | 'medium' | 'hard';
  estimated_monthly_traffic: string;
  free_tier: boolean;
  tags: string[];
}

export const DIRECTORIES: DirectoryEntry[] = [
  // ===== AI Tool Directories =====
  {
    slug: 'theresanaiforthat',
    name: "There's An AI For That",
    url: 'https://theresanaiforthat.com/submit/',
    category: 'ai-tools',
    description: 'Largest AI tool directory with 10K+ tools listed. High domain authority and strong organic traffic.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '5M+',
    free_tier: true,
    tags: ['ai', 'directory', 'high-traffic'],
  },
  {
    slug: 'futuretools',
    name: 'Future Tools',
    url: 'https://futuretools.io/submit-a-tool',
    category: 'ai-tools',
    description: 'Curated AI tools directory by Matt Wolfe. Strong YouTube audience drives traffic.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '1M+',
    free_tier: true,
    tags: ['ai', 'curated', 'youtube'],
  },
  {
    slug: 'toolify',
    name: 'Toolify.ai',
    url: 'https://toolify.ai/submit',
    category: 'ai-tools',
    description: 'AI tools directory with rankings, reviews, and traffic estimates for each tool.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '2M+',
    free_tier: true,
    tags: ['ai', 'rankings', 'analytics'],
  },
  {
    slug: 'topai-tools',
    name: 'TopAI.tools',
    url: 'https://topai.tools/submit',
    category: 'ai-tools',
    description: 'AI tool aggregator with category-based browsing and user reviews.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '500K',
    free_tier: true,
    tags: ['ai', 'reviews'],
  },
  {
    slug: 'aiscout',
    name: 'AI Scout',
    url: 'https://aiscout.net/submit/',
    category: 'ai-tools',
    description: 'AI tool discovery platform with daily featured tools and newsletters.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '100K',
    free_tier: true,
    tags: ['ai', 'newsletter', 'featured'],
  },
  {
    slug: 'aitool-guru',
    name: 'AI Tool Guru',
    url: 'https://aitool.guru/submit',
    category: 'ai-tools',
    description: 'AI tools database with detailed reviews, pricing comparisons, and alternatives.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '200K',
    free_tier: true,
    tags: ['ai', 'reviews', 'pricing'],
  },
  {
    slug: 'aicyclopedia',
    name: 'AIcyclopedia',
    url: 'https://aicyclopedia.com/submit/',
    category: 'ai-tools',
    description: 'Encyclopedia-style AI directory with comprehensive tool breakdowns.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '100K',
    free_tier: true,
    tags: ['ai', 'encyclopedia'],
  },
  {
    slug: 'futurepedia',
    name: 'Futurepedia',
    url: 'https://futurepedia.io/submit-tool',
    category: 'ai-tools',
    description: 'Large AI tools directory with 5K+ tools. Categorized and searchable with daily updates.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '1M+',
    free_tier: true,
    tags: ['ai', 'large-directory'],
  },
  {
    slug: 'aitoolsdirectory',
    name: 'AI Tools Directory',
    url: 'https://aitoolsdirectory.com/submit',
    category: 'ai-tools',
    description: 'Simple, clean directory of AI tools organized by use case.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '150K',
    free_tier: true,
    tags: ['ai', 'simple'],
  },
  {
    slug: 'aitools-fyi',
    name: 'AITools.fyi',
    url: 'https://aitools.fyi/submit',
    category: 'ai-tools',
    description: 'Growing AI tools directory with featured listings and email newsletter.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '80K',
    free_tier: true,
    tags: ['ai', 'newsletter'],
  },
  {
    slug: 'supertools',
    name: 'SuperTools',
    url: 'https://supertools.therundown.ai/submit',
    category: 'ai-tools',
    description: 'AI tools directory from The Rundown AI newsletter. Huge newsletter audience.',
    has_api: false,
    difficulty: 'medium',
    estimated_monthly_traffic: '300K',
    free_tier: true,
    tags: ['ai', 'newsletter', 'featured'],
  },
  {
    slug: 'whattheai',
    name: 'WhatTheAI',
    url: 'https://whattheai.tech/submit',
    category: 'ai-tools',
    description: 'AI directory focused on practical AI tools for everyday tasks.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '50K',
    free_tier: true,
    tags: ['ai', 'practical'],
  },
  {
    slug: 'opentools',
    name: 'OpenTools',
    url: 'https://opentools.ai/submit',
    category: 'ai-tools',
    description: 'Open-source and free AI tools directory. Good for developer tools.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '100K',
    free_tier: true,
    tags: ['ai', 'open-source', 'free'],
  },
  {
    slug: 'insidr-ai',
    name: 'Insidr.ai',
    url: 'https://insidr.ai/submit-tool/',
    category: 'ai-tools',
    description: 'AI tools directory with detailed guides on how to use AI tools effectively.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '200K',
    free_tier: true,
    tags: ['ai', 'guides', 'tutorials'],
  },
  {
    slug: 'gptstore-ai',
    name: 'GPT Store',
    url: 'https://gptstore.ai/submit',
    category: 'ai-tools',
    description: 'Directory focused on GPTs, AI agents, and ChatGPT plugins.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '300K',
    free_tier: true,
    tags: ['ai', 'gpt', 'chatgpt', 'plugins'],
  },

  // ===== Product Directories =====
  {
    slug: 'producthunt',
    name: 'Product Hunt',
    url: 'https://producthunt.com/posts/new',
    category: 'product',
    description: 'The #1 product launch platform. Requires community support for visibility. Plan your launch day carefully.',
    has_api: true,
    difficulty: 'hard',
    estimated_monthly_traffic: '5M+',
    free_tier: true,
    tags: ['launch', 'community', 'must-do'],
  },
  {
    slug: 'betalist',
    name: 'BetaList',
    url: 'https://betalist.com/submit',
    category: 'product',
    description: 'Directory for pre-launch and beta products. Great for early adopter acquisition.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '200K',
    free_tier: true,
    tags: ['beta', 'pre-launch', 'early-adopters'],
  },
  {
    slug: 'alternativeto',
    name: 'AlternativeTo',
    url: 'https://alternativeto.net/submit/',
    category: 'product',
    description: 'Find alternatives to any software. Submit as an alternative to competitors. High SEO value.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '3M+',
    free_tier: true,
    tags: ['alternatives', 'seo', 'comparison'],
  },
  {
    slug: 'g2',
    name: 'G2',
    url: 'https://www.g2.com/products/new',
    category: 'product',
    description: 'Enterprise software review platform. Slow approval but extremely high authority for B2B.',
    has_api: true,
    difficulty: 'hard',
    estimated_monthly_traffic: '5M+',
    free_tier: true,
    tags: ['enterprise', 'reviews', 'b2b'],
  },
  {
    slug: 'capterra',
    name: 'Capterra',
    url: 'https://www.capterra.com/vendors/sign-up',
    category: 'product',
    description: 'Software review and comparison platform owned by Gartner. Free basic listing available.',
    has_api: false,
    difficulty: 'medium',
    estimated_monthly_traffic: '3M+',
    free_tier: true,
    tags: ['reviews', 'enterprise', 'gartner'],
  },
  {
    slug: 'getapp',
    name: 'GetApp',
    url: 'https://www.getapp.com/submit/',
    category: 'product',
    description: 'Software discovery platform by Gartner. Category-based browsing with comparison features.',
    has_api: false,
    difficulty: 'medium',
    estimated_monthly_traffic: '1M+',
    free_tier: true,
    tags: ['reviews', 'comparison', 'gartner'],
  },
  {
    slug: 'saashub',
    name: 'SaaSHub',
    url: 'https://www.saashub.com/submit',
    category: 'product',
    description: 'Independent SaaS discovery platform. Shows alternatives and provides trend data.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '500K',
    free_tier: true,
    tags: ['saas', 'alternatives', 'trends'],
  },
  {
    slug: 'stackshare',
    name: 'StackShare',
    url: 'https://stackshare.io/submit',
    category: 'product',
    description: 'Tech stack discovery. Companies share their stacks, great for developer tools.',
    has_api: true,
    difficulty: 'medium',
    estimated_monthly_traffic: '1M+',
    free_tier: true,
    tags: ['techstack', 'developer', 'engineering'],
  },
  {
    slug: 'slant',
    name: 'Slant',
    url: 'https://www.slant.co/',
    category: 'product',
    description: 'Community-driven product recommendations with pros/cons comparisons.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '500K',
    free_tier: true,
    tags: ['recommendations', 'community', 'comparison'],
  },
  {
    slug: 'softwareadvice',
    name: 'Software Advice',
    url: 'https://www.softwareadvice.com/vendors/',
    category: 'product',
    description: 'Gartner-owned B2B software review platform. Connects buyers with vendors.',
    has_api: false,
    difficulty: 'medium',
    estimated_monthly_traffic: '2M+',
    free_tier: true,
    tags: ['b2b', 'reviews', 'gartner'],
  },
  {
    slug: 'sourceforge',
    name: 'SourceForge',
    url: 'https://sourceforge.net/create/',
    category: 'product',
    description: 'Veteran software directory. Still gets significant traffic for open-source and commercial tools.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '2M+',
    free_tier: true,
    tags: ['software', 'open-source', 'legacy'],
  },
  {
    slug: 'crozdesk',
    name: 'Crozdesk',
    url: 'https://crozdesk.com/vendors',
    category: 'product',
    description: 'B2B software reviews platform. Good for niche categories with less competition.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '200K',
    free_tier: true,
    tags: ['b2b', 'reviews', 'niche'],
  },

  // ===== Startup Directories =====
  {
    slug: 'indiehackers',
    name: 'Indie Hackers',
    url: 'https://www.indiehackers.com/products',
    category: 'startup',
    description: 'Community of bootstrapped founders. Product listing + community engagement. Very engaged audience.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '1M+',
    free_tier: true,
    tags: ['indie', 'bootstrap', 'community'],
  },
  {
    slug: 'betapage',
    name: 'BetaPage',
    url: 'https://betapage.co/submit-startup',
    category: 'startup',
    description: 'Directory for new startups and beta products. Quick approval process.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '100K',
    free_tier: true,
    tags: ['beta', 'startups'],
  },
  {
    slug: 'startupbase',
    name: 'StartupBase',
    url: 'https://startupbase.io/submit',
    category: 'startup',
    description: 'Simple startup directory with category browsing. Quick listing process.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '50K',
    free_tier: true,
    tags: ['startups', 'simple'],
  },
  {
    slug: 'launchingnext',
    name: 'Launching Next',
    url: 'https://www.launchingnext.com/submit/',
    category: 'startup',
    description: 'Startup discovery platform featuring new products daily.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '50K',
    free_tier: true,
    tags: ['startups', 'launch', 'daily-featured'],
  },
  {
    slug: 'startupstash',
    name: 'StartupStash',
    url: 'https://startupstash.com/add-listing/',
    category: 'startup',
    description: 'Curated directory of startup tools and resources. Good domain authority.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '200K',
    free_tier: true,
    tags: ['startups', 'tools', 'curated'],
  },
  {
    slug: 'f6s',
    name: 'F6S',
    url: 'https://www.f6s.com/',
    category: 'startup',
    description: 'Startup platform with funding, accelerator applications, and company profiles.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '500K',
    free_tier: true,
    tags: ['startups', 'funding', 'accelerators'],
  },
  {
    slug: 'wellfound',
    name: 'Wellfound (AngelList)',
    url: 'https://wellfound.com/',
    category: 'startup',
    description: 'Startup job board and company directory. Formerly AngelList Talent.',
    has_api: true,
    difficulty: 'medium',
    estimated_monthly_traffic: '3M+',
    free_tier: true,
    tags: ['startups', 'jobs', 'angellist'],
  },
  {
    slug: 'crunchbase',
    name: 'Crunchbase',
    url: 'https://www.crunchbase.com/add-new',
    category: 'startup',
    description: 'Company data platform for startups and enterprises. High authority backlink.',
    has_api: true,
    difficulty: 'medium',
    estimated_monthly_traffic: '5M+',
    free_tier: true,
    tags: ['data', 'funding', 'authority'],
  },
  {
    slug: 'startupranking',
    name: 'Startup Ranking',
    url: 'https://www.startupranking.com/startups/add',
    category: 'startup',
    description: 'Global startup ranking platform. Tracks and ranks startups by various metrics.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '200K',
    free_tier: true,
    tags: ['startups', 'ranking'],
  },
  {
    slug: 'killerstartups',
    name: 'KillerStartups',
    url: 'https://killerstartups.com/submit-startup/',
    category: 'startup',
    description: 'Long-running startup directory. Editorial reviews with featured placements.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '100K',
    free_tier: true,
    tags: ['startups', 'editorial'],
  },
  {
    slug: 'launched',
    name: 'Launched',
    url: 'https://launched.io/submit',
    category: 'startup',
    description: 'Curated launch directory. Highlights new startups and side projects.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '30K',
    free_tier: true,
    tags: ['startups', 'launch', 'side-project'],
  },
  {
    slug: 'startupbuffer',
    name: 'StartupBuffer',
    url: 'https://startupbuffer.com/site/submit',
    category: 'startup',
    description: 'Startup promotion platform with daily featured startups.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '30K',
    free_tier: true,
    tags: ['startups', 'promotion'],
  },
  {
    slug: 'getworm',
    name: 'GetWorm',
    url: 'https://getworm.com/submit-startup',
    category: 'startup',
    description: 'Startup showcase platform connecting founders with early adopters.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '20K',
    free_tier: true,
    tags: ['startups', 'early-adopters'],
  },
  {
    slug: 'springwise',
    name: 'Springwise',
    url: 'https://www.springwise.com/submit-an-innovation/',
    category: 'startup',
    description: 'Innovation intelligence platform. Covers new business ideas and innovations.',
    has_api: false,
    difficulty: 'medium',
    estimated_monthly_traffic: '200K',
    free_tier: true,
    tags: ['innovation', 'trends'],
  },

  // ===== Developer Tool Directories =====
  {
    slug: 'devhunt',
    name: 'DevHunt',
    url: 'https://devhunt.org/',
    category: 'developer',
    description: 'Product Hunt for developer tools. GitHub-powered launches with community voting.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '100K',
    free_tier: true,
    tags: ['developer', 'github', 'launch'],
  },
  {
    slug: 'libhunt',
    name: 'LibHunt',
    url: 'https://www.libhunt.com/',
    category: 'developer',
    description: 'Discover trending open-source projects and libraries. Good for developer tools.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '300K',
    free_tier: true,
    tags: ['developer', 'open-source', 'libraries'],
  },
  {
    slug: 'awesome-lists',
    name: 'Awesome Lists',
    url: 'https://github.com/topics/awesome-list',
    category: 'developer',
    description: 'Curated lists on GitHub. Find relevant awesome-lists and submit PRs to get listed.',
    has_api: false,
    difficulty: 'medium',
    estimated_monthly_traffic: '1M+',
    free_tier: true,
    tags: ['github', 'curated', 'community'],
  },
  {
    slug: 'console-dev',
    name: 'Console.dev',
    url: 'https://console.dev/submit/',
    category: 'developer',
    description: 'Weekly newsletter featuring the best developer tools. Editorial selection process.',
    has_api: false,
    difficulty: 'medium',
    estimated_monthly_traffic: '50K',
    free_tier: true,
    tags: ['developer', 'newsletter', 'editorial'],
  },
  {
    slug: 'devresources',
    name: 'Dev Resources',
    url: 'https://devresourc.es/submit',
    category: 'developer',
    description: 'Curated list of developer resources, tools, and services.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '50K',
    free_tier: true,
    tags: ['developer', 'resources', 'curated'],
  },
  {
    slug: 'uneed',
    name: 'Uneed',
    url: 'https://uneed.best/submit',
    category: 'developer',
    description: 'Developer-focused product directory with daily launches.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '30K',
    free_tier: true,
    tags: ['developer', 'launch'],
  },
  {
    slug: 'openalternative',
    name: 'OpenAlternative',
    url: 'https://openalternative.co/submit',
    category: 'developer',
    description: 'Open-source alternatives to popular tools. Great for developer and SaaS tools.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '100K',
    free_tier: true,
    tags: ['open-source', 'alternatives', 'developer'],
  },
  {
    slug: 'free-for-dev',
    name: 'Free for Dev',
    url: 'https://github.com/ripienaar/free-for-dev',
    category: 'developer',
    description: 'Massive curated list of services with free tiers for developers. Submit via GitHub PR.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '500K',
    free_tier: true,
    tags: ['developer', 'free-tier', 'github'],
  },
  {
    slug: 'saas-pages',
    name: 'SaaS Pages',
    url: 'https://saaspages.xyz/submit',
    category: 'developer',
    description: 'Collection of SaaS landing pages for design inspiration. Submit your landing page.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '30K',
    free_tier: true,
    tags: ['saas', 'design', 'landing-pages'],
  },

  // ===== SEO / Link Building =====
  {
    slug: 'webdirectories',
    name: 'Best of the Web',
    url: 'https://botw.org/helpcenter/submitasite.aspx',
    category: 'seo',
    description: 'One of the oldest web directories. Good for general SEO backlinks.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '100K',
    free_tier: true,
    tags: ['seo', 'backlinks', 'directory'],
  },
  {
    slug: 'jasminedirectory',
    name: 'Jasmine Directory',
    url: 'https://www.jasminedirectory.com/submit.html',
    category: 'seo',
    description: 'Human-edited web directory with quality standards. Good for SEO.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '50K',
    free_tier: true,
    tags: ['seo', 'backlinks', 'human-edited'],
  },
  {
    slug: 'hotfrog',
    name: 'Hotfrog',
    url: 'https://www.hotfrog.com/',
    category: 'seo',
    description: 'Business directory with free listings. Available in many countries.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '300K',
    free_tier: true,
    tags: ['seo', 'business', 'local'],
  },
  {
    slug: 'aboutus',
    name: 'AboutUs',
    url: 'https://www.aboutus.com/',
    category: 'seo',
    description: 'Web directory with domain information and website profiles.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '100K',
    free_tier: true,
    tags: ['seo', 'domain', 'profile'],
  },
  {
    slug: 'ezilon',
    name: 'Ezilon',
    url: 'https://www.ezilon.com/submit.htm',
    category: 'seo',
    description: 'Regional web directory organized by geography and category.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '50K',
    free_tier: true,
    tags: ['seo', 'regional', 'directory'],
  },
  {
    slug: 'sitepromotiondirectory',
    name: 'Site Promotion Directory',
    url: 'https://www.sitepromotion.com/',
    category: 'seo',
    description: 'SEO-focused directory for website promotion and link building.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '30K',
    free_tier: true,
    tags: ['seo', 'promotion'],
  },
  {
    slug: 'bloggingfusion',
    name: 'Blogging Fusion',
    url: 'https://www.bloggingfusion.com/submit-website/',
    category: 'seo',
    description: 'Blog and website directory. Good for content-heavy sites and blogs.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '50K',
    free_tier: true,
    tags: ['seo', 'blogs', 'content'],
  },

  // ===== Social Bookmarking / Communities =====
  {
    slug: 'hackernews',
    name: 'Hacker News (Show HN)',
    url: 'https://news.ycombinator.com/submit',
    category: 'social',
    description: 'Show HN is the gold standard for developer product launches. Massive engaged audience of builders.',
    has_api: true,
    difficulty: 'hard',
    estimated_monthly_traffic: '10M+',
    free_tier: true,
    tags: ['community', 'developer', 'launch', 'must-do'],
  },
  {
    slug: 'reddit-saas',
    name: 'Reddit r/SaaS',
    url: 'https://www.reddit.com/r/SaaS/submit',
    category: 'social',
    description: 'SaaS-focused subreddit. Share product updates, ask for feedback, and engage with SaaS community.',
    has_api: true,
    difficulty: 'medium',
    estimated_monthly_traffic: '500K',
    free_tier: true,
    tags: ['community', 'saas', 'feedback'],
  },
  {
    slug: 'reddit-startups',
    name: 'Reddit r/startups',
    url: 'https://www.reddit.com/r/startups/submit',
    category: 'social',
    description: 'Startup-focused subreddit. Share launches and get community feedback.',
    has_api: true,
    difficulty: 'medium',
    estimated_monthly_traffic: '1M+',
    free_tier: true,
    tags: ['community', 'startups', 'feedback'],
  },
  {
    slug: 'reddit-sideproject',
    name: 'Reddit r/SideProject',
    url: 'https://www.reddit.com/r/SideProject/submit',
    category: 'social',
    description: 'Community for side projects. Good for early-stage launches and feedback.',
    has_api: true,
    difficulty: 'easy',
    estimated_monthly_traffic: '200K',
    free_tier: true,
    tags: ['community', 'side-project', 'feedback'],
  },
  {
    slug: 'reddit-internetisbeautiful',
    name: 'Reddit r/InternetIsBeautiful',
    url: 'https://www.reddit.com/r/InternetIsBeautiful/submit',
    category: 'social',
    description: 'Subreddit for interesting websites and tools. Can drive massive traffic if post goes viral.',
    has_api: true,
    difficulty: 'hard',
    estimated_monthly_traffic: '2M+',
    free_tier: true,
    tags: ['community', 'viral', 'high-potential'],
  },
  {
    slug: 'reddit-webdev',
    name: 'Reddit r/webdev',
    url: 'https://www.reddit.com/r/webdev/submit',
    category: 'social',
    description: 'Web development community. Good for developer tools and web-related products.',
    has_api: true,
    difficulty: 'medium',
    estimated_monthly_traffic: '1M+',
    free_tier: true,
    tags: ['community', 'developer', 'webdev'],
  },
  {
    slug: 'reddit-entrepreneur',
    name: 'Reddit r/Entrepreneur',
    url: 'https://www.reddit.com/r/Entrepreneur/submit',
    category: 'social',
    description: 'Large entrepreneurship community. Share your journey and get feedback.',
    has_api: true,
    difficulty: 'medium',
    estimated_monthly_traffic: '2M+',
    free_tier: true,
    tags: ['community', 'entrepreneur', 'business'],
  },
  {
    slug: 'lobsters',
    name: 'Lobste.rs',
    url: 'https://lobste.rs/',
    category: 'social',
    description: 'Invite-only tech community. High signal-to-noise ratio. Must get an invite from existing member.',
    has_api: true,
    difficulty: 'hard',
    estimated_monthly_traffic: '200K',
    free_tier: true,
    tags: ['community', 'developer', 'invite-only'],
  },
  {
    slug: 'devto',
    name: 'Dev.to',
    url: 'https://dev.to/',
    category: 'social',
    description: 'Developer blogging platform. Write about your product, share tutorials, and build audience.',
    has_api: true,
    difficulty: 'easy',
    estimated_monthly_traffic: '5M+',
    free_tier: true,
    tags: ['blog', 'developer', 'content'],
  },
  {
    slug: 'hashnode',
    name: 'Hashnode',
    url: 'https://hashnode.com/',
    category: 'social',
    description: 'Developer blogging platform with custom domains. Good for building technical authority.',
    has_api: true,
    difficulty: 'easy',
    estimated_monthly_traffic: '3M+',
    free_tier: true,
    tags: ['blog', 'developer', 'custom-domain'],
  },
  {
    slug: 'medium',
    name: 'Medium',
    url: 'https://medium.com/new-story',
    category: 'social',
    description: 'Popular blogging platform. Write product stories and thought leadership content.',
    has_api: true,
    difficulty: 'easy',
    estimated_monthly_traffic: '100M+',
    free_tier: true,
    tags: ['blog', 'writing', 'audience'],
  },
  {
    slug: 'twitter-launch',
    name: 'Twitter/X Launch',
    url: 'https://twitter.com/compose/tweet',
    category: 'social',
    description: 'Announce your launch on Twitter/X. Tag relevant communities and use launch hashtags.',
    has_api: true,
    difficulty: 'easy',
    estimated_monthly_traffic: '500M+',
    free_tier: true,
    tags: ['social-media', 'launch', 'must-do'],
  },
  {
    slug: 'linkedin-launch',
    name: 'LinkedIn Launch Post',
    url: 'https://www.linkedin.com/',
    category: 'social',
    description: 'Share your launch on LinkedIn. Great for B2B and professional networks.',
    has_api: true,
    difficulty: 'easy',
    estimated_monthly_traffic: '300M+',
    free_tier: true,
    tags: ['social-media', 'b2b', 'professional'],
  },

  // ===== Review Sites =====
  {
    slug: 'trustradius',
    name: 'TrustRadius',
    url: 'https://www.trustradius.com/vendor',
    category: 'review',
    description: 'B2B review platform with detailed, authenticated reviews. Good for enterprise credibility.',
    has_api: true,
    difficulty: 'medium',
    estimated_monthly_traffic: '2M+',
    free_tier: true,
    tags: ['reviews', 'b2b', 'enterprise'],
  },
  {
    slug: 'trustpilot',
    name: 'Trustpilot',
    url: 'https://business.trustpilot.com/',
    category: 'review',
    description: 'Consumer trust and review platform. Claim your profile and collect customer reviews.',
    has_api: true,
    difficulty: 'easy',
    estimated_monthly_traffic: '30M+',
    free_tier: true,
    tags: ['reviews', 'trust', 'consumer'],
  },
  {
    slug: 'gartner-peer-insights',
    name: 'Gartner Peer Insights',
    url: 'https://www.gartner.com/reviews/vendor-listing',
    category: 'review',
    description: 'Enterprise-grade review platform by Gartner. Excellent for B2B credibility.',
    has_api: false,
    difficulty: 'hard',
    estimated_monthly_traffic: '1M+',
    free_tier: true,
    tags: ['reviews', 'enterprise', 'gartner'],
  },
  {
    slug: 'saasworthy',
    name: 'SaaSworthy',
    url: 'https://www.saasworthy.com/submit',
    category: 'review',
    description: 'SaaS review and comparison platform. Good for building social proof.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '200K',
    free_tier: true,
    tags: ['reviews', 'saas', 'comparison'],
  },
  {
    slug: 'goodfirms',
    name: 'GoodFirms',
    url: 'https://www.goodfirms.co/add-product',
    category: 'review',
    description: 'IT company and software reviews. Rankings based on multiple quality criteria.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '500K',
    free_tier: true,
    tags: ['reviews', 'rankings', 'it'],
  },

  // ===== Free Tools / Listings =====
  {
    slug: 'google-business',
    name: 'Google Business Profile',
    url: 'https://business.google.com/',
    category: 'free-listing',
    description: 'Free Google listing. Essential for local SEO and appearing in Google search/maps.',
    has_api: true,
    difficulty: 'easy',
    estimated_monthly_traffic: '1B+',
    free_tier: true,
    tags: ['google', 'local-seo', 'must-do'],
  },
  {
    slug: 'bing-places',
    name: 'Bing Places',
    url: 'https://www.bingplaces.com/',
    category: 'free-listing',
    description: 'Free Bing business listing. Import from Google Business for quick setup.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '100M+',
    free_tier: true,
    tags: ['bing', 'local-seo'],
  },
  {
    slug: 'apple-maps',
    name: 'Apple Maps Connect',
    url: 'https://mapsconnect.apple.com/',
    category: 'free-listing',
    description: 'Add your business to Apple Maps. Important for iOS users and Siri.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '50M+',
    free_tier: true,
    tags: ['apple', 'local-seo', 'maps'],
  },
  {
    slug: 'yelp',
    name: 'Yelp',
    url: 'https://biz.yelp.com/',
    category: 'free-listing',
    description: 'Claim your Yelp business profile. Good for local SEO and customer reviews.',
    has_api: true,
    difficulty: 'easy',
    estimated_monthly_traffic: '50M+',
    free_tier: true,
    tags: ['reviews', 'local-seo', 'business'],
  },
  {
    slug: 'yellowpages',
    name: 'YellowPages',
    url: 'https://www.yellowpages.com/',
    category: 'free-listing',
    description: 'Online business directory. Free listing with basic info.',
    has_api: false,
    difficulty: 'easy',
    estimated_monthly_traffic: '10M+',
    free_tier: true,
    tags: ['directory', 'business', 'local'],
  },
  {
    slug: 'bbb',
    name: 'Better Business Bureau',
    url: 'https://www.bbb.org/get-listed',
    category: 'free-listing',
    description: 'Business accreditation and listing. Builds consumer trust and credibility.',
    has_api: false,
    difficulty: 'medium',
    estimated_monthly_traffic: '10M+',
    free_tier: true,
    tags: ['trust', 'accreditation', 'business'],
  },
  {
    slug: 'foursquare',
    name: 'Foursquare',
    url: 'https://foursquare.com/add-place',
    category: 'free-listing',
    description: 'Location intelligence platform. Claim your business listing.',
    has_api: true,
    difficulty: 'easy',
    estimated_monthly_traffic: '5M+',
    free_tier: true,
    tags: ['location', 'local-seo'],
  },
  {
    slug: 'pinterest',
    name: 'Pinterest Business',
    url: 'https://business.pinterest.com/',
    category: 'free-listing',
    description: 'Create product pins and drive traffic from visual search. Good for SaaS screenshots.',
    has_api: true,
    difficulty: 'easy',
    estimated_monthly_traffic: '400M+',
    free_tier: true,
    tags: ['visual', 'social', 'seo'],
  },
  {
    slug: 'github-marketplace',
    name: 'GitHub Marketplace',
    url: 'https://github.com/marketplace',
    category: 'free-listing',
    description: 'List your developer tool on GitHub Marketplace. Reach millions of developers.',
    has_api: true,
    difficulty: 'medium',
    estimated_monthly_traffic: '50M+',
    free_tier: true,
    tags: ['developer', 'github', 'marketplace'],
  },
  {
    slug: 'chrome-web-store',
    name: 'Chrome Web Store',
    url: 'https://chrome.google.com/webstore/devconsole',
    category: 'free-listing',
    description: 'Publish Chrome extensions. If you have a browser extension, this is essential.',
    has_api: false,
    difficulty: 'medium',
    estimated_monthly_traffic: '100M+',
    free_tier: true,
    tags: ['extension', 'chrome', 'google'],
  },
  {
    slug: 'vscode-marketplace',
    name: 'VS Code Marketplace',
    url: 'https://marketplace.visualstudio.com/manage',
    category: 'free-listing',
    description: 'Publish VS Code extensions. Great visibility among developers.',
    has_api: true,
    difficulty: 'medium',
    estimated_monthly_traffic: '20M+',
    free_tier: true,
    tags: ['developer', 'vscode', 'extension'],
  },
  {
    slug: 'npm-registry',
    name: 'npm Registry',
    url: 'https://www.npmjs.com/',
    category: 'free-listing',
    description: 'Publish JavaScript/Node.js packages. Essential for developer tools and SDKs.',
    has_api: true,
    difficulty: 'easy',
    estimated_monthly_traffic: '20M+',
    free_tier: true,
    tags: ['developer', 'npm', 'javascript'],
  },
];

export function getDirectoriesByCategory(category?: string): DirectoryEntry[] {
  if (!category) return DIRECTORIES;
  return DIRECTORIES.filter(d => d.category === category);
}

export function getDirectoryBySlug(slug: string): DirectoryEntry | undefined {
  return DIRECTORIES.find(d => d.slug === slug);
}

export function generateSubmissionData(brandConfig: {
  brand_name: string;
  brand_url: string | null;
  brand_aliases: string;
  competitors: string;
}): {
  name: string;
  url: string;
  tagline: string;
  description: string;
  category: string;
  tags: string[];
} {
  const aliases: string[] = JSON.parse(brandConfig.brand_aliases || '[]');
  const competitors: { name: string }[] = JSON.parse(brandConfig.competitors || '[]');

  return {
    name: brandConfig.brand_name,
    url: brandConfig.brand_url || '',
    tagline: `${brandConfig.brand_name} -- AI visibility monitoring for startups`,
    description: `${brandConfig.brand_name} helps startups track if AI assistants like ChatGPT, Claude, and Gemini mention their product. Monitor brand visibility, optimize content for AI citation, and track social mentions -- all in one platform.${aliases.length > 0 ? ` Also known as: ${aliases.join(', ')}.` : ''}${competitors.length > 0 ? ` Competes with: ${competitors.map(c => c.name).join(', ')}.` : ''}`,
    category: 'AI Tools / Marketing / Analytics',
    tags: ['ai', 'marketing', 'seo', 'analytics', 'brand-monitoring', 'saas'],
  };
}
