#!/bin/bash
set -e

cd "$(dirname "$0")/../packages/badge-widget"
bun run build.ts

# Inline the built JS into a TypeScript constant for the worker
node -e "
  const fs = require('fs');
  const js = fs.readFileSync('dist/mentionpilot-badge.min.js', 'utf-8');
  const out = '// Auto-generated by scripts/build-badge.sh — do not edit manually\nexport const WIDGET_JS = ' + JSON.stringify(js) + ';\n';
  fs.writeFileSync('../../workers/api/src/routes/badge-widget-bundle.ts', out);
"

echo "Badge widget built and inlined successfully."
